"use client";
import {useEffect,useState} from "react";

type Setting={course_slug:string;provider:string;checkout_url:string;active:number};
const courseNames:Record<string,string>={"due-diligence":"Due Diligence Imobiliária",arrematacao:"Arrematação Judicial",incorporacao:"Registro de Incorporação"};

export default function CheckoutSettings(){
  const [settings,setSettings]=useState<Setting[]>([]);const [message,setMessage]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);
  useEffect(()=>{fetch("/api/admin/checkout-settings").then(r=>r.json()).then(d=>setSettings(d.settings||[])).catch(()=>{})},[]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage("");setError("");const form=new FormData(e.currentTarget);const body={courseSlug:form.get("courseSlug"),provider:form.get("provider"),checkoutUrl:form.get("checkoutUrl"),active:form.get("active")==="on"};const response=await fetch("/api/admin/checkout-settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();setLoading(false);if(!response.ok){setError(data.error||"Não foi possível salvar.");return}setMessage("Link de pagamento salvo e ativado.");setSettings(current=>[...current.filter(s=>s.course_slug!==data.courseSlug),{course_slug:data.courseSlug,provider:data.provider,checkout_url:data.checkoutUrl,active:data.active?1:0}]);}
  return <section className="admin-checkout"><div className="admin-section-title"><span className="eyebrow">Checkout dos cursos</span><h2>Configurar a plataforma de pagamento</h2><p>Cole o link gerado pela Hotmart, Eduzz ou outra plataforma. O botão do curso passará a encaminhar o comprador para esse endereço.</p></div><form className="grant-form" onSubmit={submit}><label>Curso<select name="courseSlug" required><option value="due-diligence">Due Diligence Imobiliária</option><option value="arrematacao">Arrematação Judicial</option><option value="incorporacao">Registro de Incorporação</option></select></label><label>Plataforma<select name="provider" required><option>Hotmart</option><option>Eduzz</option><option>Kiwify</option><option>Monetizze</option><option>Outro</option></select></label><label>Link do checkout<input name="checkoutUrl" type="url" required placeholder="https://pay.hotmart.com/..."/><small>Use o endereço completo fornecido pela plataforma.</small></label><label className="check-label"><input name="active" type="checkbox" defaultChecked/> Ativar este checkout imediatamente</label><button className="button primary" disabled={loading}>{loading?"Salvando…":"Salvar link de pagamento"}</button>{error&&<p className="form-error">{error}</p>}{message&&<p className="form-success">{message}</p>}</form>{settings.length>0&&<div className="checkout-list"><h3>Links configurados</h3>{settings.map(s=><article key={s.course_slug}><div><strong>{courseNames[s.course_slug]}</strong><small>{s.provider} · {s.active?"ativo":"inativo"}</small></div><a href={s.checkout_url} target="_blank" rel="noreferrer">Testar checkout ↗</a></article>)}</div>}</section>;
}
