import Link from "next/link";

export const metadata={title:"Trajetória · Paula Gomes de Magalhães"};

function SocialIcon({name}:{name:"linkedin"|"instagram"|"lattes"}){
  if(name==="linkedin") return <svg className="social-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.45 20.45h-3.56v-5.57c0-1.33-.03-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.34V8.98h3.42v1.57h.05c.48-.9 1.64-1.85 3.37-1.85 3.61 0 4.27 2.37 4.27 5.46v6.29ZM5.32 7.41a2.06 2.06 0 1 1 0-4.12 2.06 2.06 0 0 1 0 4.12ZM7.1 20.45H3.54V8.98H7.1v11.47Z"/></svg>;
  if(name==="instagram") return <svg className="social-icon" viewBox="0 0 24 24" aria-hidden="true"><path fillRule="evenodd" d="M7.8 2h8.4A5.8 5.8 0 0 1 22 7.8v8.4a5.8 5.8 0 0 1-5.8 5.8H7.8A5.8 5.8 0 0 1 2 16.2V7.8A5.8 5.8 0 0 1 7.8 2Zm8.2 2H8a4 4 0 0 0-4 4v8a4 4 0 0 0 4 4h8a4 4 0 0 0 4-4V8a4 4 0 0 0-4-4Zm-4 3.14A4.86 4.86 0 1 1 12 16.86a4.86 4.86 0 0 1 0-9.72Zm0 2A2.86 2.86 0 1 0 12 14.86a2.86 2.86 0 0 0 0-5.72Zm5.1-2.28a1.16 1.16 0 1 1 0-2.32 1.16 1.16 0 0 1 0 2.32Z"/></svg>;
  return <svg className="social-icon lattes-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2 2.5 7.1 12 12l7.5-3.9v5.7h2V7.1L12 2Zm-6.1 9.4v4.3c0 2.5 2.8 4.4 6.1 4.4s6.1-1.9 6.1-4.4v-4.3L12 14.6l-6.1-3.2Z"/></svg>;
}

const works=[
  {label:"Tese",title:"Incorporação Imobiliária: uso de sistemas tecnológicos para avaliação legislativo-regulatória.",href:"https://repositorio.ufmg.br/items/b4ce3c5c-94d7-44cf-860b-0f5e37f7f5dc"},
  {label:"Artigo",title:"Eficiência e limites da SCP nas incorporações imobiliárias"},
  {label:"Artigo · ConJur",title:"Uso de aplicativo para avaliação legislativo-regulatória: Lei de Registros Públicos.",href:"https://conjur.com.br/2025-jun-18/uso-de-aplicativo-para-avaliacao-legislativo-regulatoria-por-uma-inovacao-nos-procedimentos-da-lei-de-registros-publicos/"},
  {label:"Artigo · ConJur",title:"Digitalizar vs. transformar o registro de imóveis: dos efeitos da Lei 14.382.",href:"https://conjur.com.br/2026-mar-24/digitalizar-vs-transformar-o-registro-de-imoveis-sobre-os-efeitos-da-lei-14-382-2/"},
  {label:"Artigo · JOTA",title:"Tecnologia e o desempenho do mercado imobiliário.",href:"https://www.jota.info/opiniao-e-analise/artigos/tecnologia-e-o-desempenho-imobiliario"},
  {label:"Capítulo de livro",title:"Modelagem de processo: instrumento para execução de políticas públicas.",href:"https://loja.editoradialetica.com/humanidades/avaliacao-legislativa-no-brasil-efeitos-da-emenda-constitucional-no-109-art-37-16?srsltid=AfmBOoqQQil9betTyqGjMemVAGUjXc6W6SVR11xehbyQXKMOxSJVTypy"},
];
const courses=[
  {title:"Due Diligence Imobiliária por Camadas",text:"Aprenda a reunir, cruzar e interpretar informações para construir o relatório do seu próprio caso.",price:"R$ 100,00",href:"/pessoal/formacao/due-diligence"},
  {title:"Arrematação Judicial de Imóveis",text:"Investigue processo, edital, matrícula, custos, ocupação e riscos antes de definir o lance.",price:"R$ 100,00",href:"/pessoal/formacao/arrematacao"},
  {title:"Registro de Incorporação Imobiliária",text:"Aprenda, do zero, a organizar e conferir a pasta do empreendimento até o protocolo.",price:"R$ 200,00",href:"/pessoal/formacao/incorporacao"},
];
const guides=[
  {title:"Guia de Boas Práticas para Registro de Incorporação Imobiliária",href:"https://gamma.app/docs/Guia-de-boas-praticas-para-o-Registro-de-Incorporacao-Imobiliaria-o1f7f6pfxl37gci?mode=doc"},
  {title:"Checklist de Incorporação Imobiliária",href:"https://docs.google.com/spreadsheets/d/1sw0BH2NeI-qql8j0EsXH1jKNwmwzuZDTNcrdXtyfY4M/edit?gid=937558841#gid=937558841"},
  {title:"Guia introdutório de Due Diligence"},
  {title:"Checklist para Arrematação"},
];
const posts=[
  {title:"Legística e mercado imobiliário: o desenho da norma importa.",href:"https://pt.linkedin.com/pulse/leg%C3%ADstica-e-mercado-imobili%C3%A1rio-o-desenho-da-norma-paula-8tzyf"},
  {title:"Quando a informação não vira conhecimento decisório.",href:"https://pt.linkedin.com/pulse/quando-informa%C3%A7%C3%A3o-n%C3%A3o-vira-conhecimento-decis%C3%B3rio-gomes-de-magalh%C3%A3es-wlwvf"},
  {title:"Quando a tecnologia repete o desenho da norma.",href:"https://pt.linkedin.com/pulse/quando-tecnologia-repete-o-desenho-da-norma-paula-gomes-de-magalh%C3%A3es-uyloe"},
];

export default function Pessoal(){return <main className="personal-main">
  <div className="page-header"><header className="top"><Link className="brand" href="/"><img className="brand-logo" src="/logo-pm.png" alt=""/><span>Paula Gomes de Magalhães<small>Pesquisa · Docência · Tecnologia</small></span></Link><nav aria-label="Navegação da trajetória"><Link className="back-link" href="/">← Página principal</Link><a href="#cursos">Cursos</a><a href="#trajetoria">Trajetória</a><a href="#publicacoes">Publicações</a><a href="#imovel123">Imóvel123</a><a href="#blog">Reflexões</a></nav></header>
  <section className="hero-split"><div className="hero-content"><div className="eyebrow">Direito registral · Legística · Tecnologia</div><h1>Pesquisa que encontra a <em>prática.</em></h1><p>Doutora e residente pós-doutoral pela UFMG, advogada, pesquisadora e docente na interface entre direito registral imobiliário, avaliação legislativo-regulatória e tecnologia.</p><div className="hero-directory" aria-label="Conteúdos disponíveis nesta página"><a href="#cursos"><b>Formação</b><span>Cursos e consultorias</span></a><a href="#publicacoes"><b>Obras</b><span>Publicações e acervo</span></a><a href="#blog"><b>Reflexões</b><span>Legística Imobiliária</span></a><a href="#imovel123"><b>Imóvel123</b><span>Tecnologia aplicada</span></a></div><div className="actions"><a className="button primary" href="#cursos">Conhecer os cursos ↓</a><a className="button" href="#trajetoria">Conhecer a trajetória →</a></div></div><div className="hero-image"><img src="/paula-enhanced.png" alt="Paula Gomes de Magalhães"/></div></section></div>

  <section className="section cream" id="trajetoria"><div className="section-title"><div className="eyebrow">01 · Trajetória</div><h2>Rigor acadêmico, experiência registral e <em>construção de soluções.</em></h2></div><div className="intro-grid"><div><p className="prose">Paula Gomes de Magalhães é residente pós-doutoral e doutora em Direito Imobiliário pela UFMG e especialista em Direito Notarial e Registral, com tese sobre incorporação imobiliária e sistemas tecnológicos para avaliação legislativo-regulatória. Sua trajetória reúne cartório, bancos, universidade, construtoras, advocacia e desenvolvimento de sistemas jurídicos.</p><div className="actions"><a className="button primary social-button" href="http://lattes.cnpq.br/2419215421377602" target="_blank" rel="noreferrer"><SocialIcon name="lattes"/>Consultar currículo Lattes ↗</a></div></div><div className="cards"><article className="card"><span className="eyebrow">Eixo I</span><h3>Direito registral imobiliário</h3><p>Qualificação registral, incorporação, regularização, cadeia dominial e segurança documental.</p></article><article className="card"><span className="eyebrow">Eixo II</span><h3>Legística e avaliação</h3><p>Desenho normativo, avaliação legislativo-regulatória e conhecimento decisório.</p></article><article className="card"><span className="eyebrow">Eixo III</span><h3>Tecnologia e linguagem</h3><p>Sistemas jurídicos, LegalTech e simplificação da linguagem especializada.</p></article></div></div></section>

  <section className="section imovel-project" id="imovel123"><div className="section-title"><div className="eyebrow">02 · Tecnologia aplicada</div><h2>Conhecimento registral transformado em <em>decisão acessível.</em></h2></div><div className="project-feature"><div><img className="imovel123-logo" src="/logo-imovel123.png" alt="Imóvel123"/><h3>Analisamos, explicamos. Você decide.</h3><p>Paula é fundadora da Imóvel123, uma frente de tecnologia dedicada à análise técnica e documental de imóveis. O projeto traduz informações registrais complexas em relatórios claros para apoiar compradores, vendedores e investidores — sem se confundir com a atuação do escritório de advocacia.</p><div className="actions"><a className="button primary" href="https://imovel123.com" target="_blank" rel="noreferrer">Conhecer a Imóvel123 ↗</a></div></div><div className="project-points"><article><b>01</b><span>Análise técnica de matrículas e documentos imobiliários</span></article><article><b>02</b><span>Informação registral apresentada em linguagem acessível</span></article><article><b>03</b><span>Tecnologia aplicada à segurança da decisão imobiliária</span></article></div></div></section>

  <section className="section" id="publicacoes"><div className="section-title"><div className="eyebrow">03 · Produção</div><h2>Obras e publicações em <em>destaque.</em></h2></div><p className="section-lead">Uma seleção dedicada ao Direito Imobiliário e Registral, à Legística e à tecnologia.</p><div className="cards publication-cards">{works.map(w=><article className="card" key={w.title}><span className="eyebrow">{w.label}</span><h3>{w.title}</h3>{w.href?<a className="card-action" href={w.href} target="_blank" rel="noreferrer">Acessar publicação ↗</a>:<small className="coming-soon">Link em breve</small>}</article>)}</div></section>

  <section className="section cream" id="cursos"><div className="section-title"><div className="eyebrow">04 · Cursos e materiais</div><h2>Aprenda com orientação e aplique ao <em>seu próprio caso.</em></h2></div><p className="section-lead">Conheça a apresentação, navegue pela demonstração e consulte a ementa. Nos cursos pagos, o percurso ensina fazendo: você trabalha no mesmo caso, constrói o próprio dossiê e pode revisá-lo durante 60 dias.</p><div className="cards course-cards paid-courses">{courses.map(c=><article className="card" key={c.title}><span className="eyebrow">Curso autoinstrucional · {c.price}</span><h3>{c.title}</h3><p>{c.text}</p><Link className="card-action" href={c.href}>Conhecer e navegar pelo curso →</Link></article>)}</div><div className="guide-heading"><div><span className="eyebrow free-materials-label">Materiais 100% gratuitos</span><h3>Guias e checklists gratuitos para consulta.</h3></div><p>Acesse gratuitamente os materiais já disponíveis. Não é necessário adquirir um curso.</p></div><div className="guide-grid">{guides.map(g=>g.href?<a className="guide-card guide-card-link" href={g.href} target="_blank" rel="noreferrer" key={g.title}><span>Material gratuito</span><h4>{g.title}</h4><b>Acessar gratuitamente ↗</b></a>:<article className="guide-card guide-card-pending" key={g.title}><span>Material gratuito</span><h4>{g.title}</h4><small>Em breve</small></article>)}</div><div className="consulting-strip"><div><span className="eyebrow">Para empresas e equipes</span><h3>Consultorias, cursos e formações personalizadas.</h3><p>Programas desenhados conforme o contexto de incorporadoras, construtoras, loteadoras, instituições e departamentos jurídicos.</p></div><a className="button primary" href="https://wa.me/5531994204205?text=Ol%C3%A1%2C%20Paula.%20Gostaria%20de%20conversar%20sobre%20uma%20consultoria%20ou%20forma%C3%A7%C3%A3o%20personalizada." target="_blank" rel="noreferrer">Solicitar proposta →</a></div></section>

  <section className="section dark" id="blog"><div className="section-title"><div className="eyebrow">05 · Legística Imobiliária</div><h2>Ideias em <em>movimento.</em></h2></div><p className="section-lead light-lead">Reflexões sobre desenho normativo, registro, tecnologia, linguagem e decisões no mercado imobiliário.</p><div className="blog-link-list">{posts.map(post=><a className="blog-link-row" href={post.href} target="_blank" rel="noreferrer" key={post.title}><span><small>Reflexão</small><h3>{post.title}</h3></span><b>Ler publicação ↗</b></a>)}</div><div className="reflection-follow"><div><span className="eyebrow">Acompanhe mais publicações</span><h3>Novas reflexões e conteúdos.</h3></div><div className="actions"><a className="button light social-button" href="https://www.linkedin.com/in/paulagomesdemagalhaes" target="_blank" rel="noreferrer"><SocialIcon name="linkedin"/>Acompanhar no LinkedIn ↗</a><a className="button social-button" href="https://www.instagram.com/paulamagalhaes_adv/" target="_blank" rel="noreferrer"><SocialIcon name="instagram"/>Acompanhar no Instagram ↗</a></div></div></section>

  <section className="section rose" id="contato"><div className="contact-box"><div><div className="eyebrow">Próximo passo</div><h2>Escolha como continuar.</h2><p>Entre em contato para cursos, pesquisa, docência e projetos, ou conheça a atuação jurídica do escritório.</p><div className="actions"><a className="button light" href="https://wa.me/5531994204205?text=Ol%C3%A1%2C%20Paula.%20Gostaria%20de%20conversar%20sobre%20seu%20trabalho." target="_blank" rel="noreferrer">Conversar pelo WhatsApp →</a><a className="button" href="mailto:paulagmagalhaesadv@gmail.com">Enviar e-mail →</a><Link className="button" href="/advocacia/">Conhecer o escritório →</Link><Link className="button" href="/">Voltar à página principal</Link></div></div><div className="contact-meta"><a href="https://wa.me/5531994204205" target="_blank" rel="noreferrer">WhatsApp: (31) 99420-4205</a><br/><a href="mailto:paulagmagalhaesadv@gmail.com">paulagmagalhaesadv@gmail.com</a><br/>Belo Horizonte · Minas Gerais<br/>Nome de citação: MAGALHÃES, P. G.</div></div></section>
</main>}
